WIP: add health checks
acorn-io/baaah pull request #60
Opened 2023-02-27 21:43 UTC by jacobdonenfeld

2023-03-03 14:49 UTC, thedadams requested changes

2023-03-03 14:49 UTC, thedadams commented on pkg/router/router.go
> +		return r.electionConfig.Run(ctx, cb)
There is one small issue here: the pod won't be ready until the `cb` is called. Which means that if the pod is a follower and not a leader, then the pod will never be marked as ready.

There needs to be a way for a follower to always be ready, but the leader should only be ready after the controllers are started.

2023-04-03 19:26 UTC, thedadams commented on pkg/healthprobes/probes.go
> +		port := obj.GetReadyzProbePort()
Already have the `port` above.

2023-04-03 19:27 UTC, thedadams commented on pkg/leader/leader.go
> +	if le.IsLeader() == false {
```suggestion
	if !le.IsLeader() {
```

2023-04-03 19:28 UTC, thedadams commented on pkg/leader/leader.go
> +					healthprobes.StartReadyzPingHandler(ec)
The next line panics, so there is no reason to start this here.

2023-04-03 19:29 UTC, thedadams commented on pkg/router/router.go
> +		healthprobes.StartReadyzPingHandler(r)
What if the follower becomes a leader? Then this will try to bind to the same port and likely error.

2023-04-20 19:50 UTC, jacobdonenfeld commented on pkg/router/router.go
> +		healthprobes.StartReadyzPingHandler(r)
Great point!

2023-05-02 12:39 UTC, thedadams commented on pkg/healthprobes/probes.go
> +			if err == nil && statusCode != http.StatusOK {
Should this be?
```suggestion
			if err == nil && statusCode == http.StatusOK {
```

2023-05-02 12:39 UTC, thedadams commented on pkg/healthprobes/probes.go
> +		healthz.InstallReadyzHandler(healthMux, watchDog)
WatchDog doesn't seem like the right name here. Regardless, I think this gets the point across.
```suggestion
		healthMux := http.NewServeMux()
		healthz.InstallReadyzHandler(healthMux, healthz.PingHealthz)
```

2023-05-02 12:39 UTC, thedadams commented on pkg/healthprobes/probes.go
> +		if resp != nil {
The documentation says that `resp.Body` is not nil whenever `err == nil`. I am not sure, but could there be situations where `resp != nil && resp.Body != nil` (which would cause a panic when trying to close the response body below?

2024-01-03 20:16 UTC, closed without merging